kind: pipeline
name: deploy

steps:
  - name: unit-test
    image: node:10
    commands:
      - node test/index.js
    when:
      branch: master
      event: push
  - name: build-image
    image: plugins/docker
    settings:
      repo: KrinaVadgama/drone-ci-demo
      username: KrinaVadgama
      password: krina@1724
      auto_tag: true
    when:
      event: tag